spring:
  application:
    name: backend

  data:
    mongodb:
      uri: mongodb+srv://akshitha:Akshitha04@cluster0.rdf62.mongodb.net/InventoryManagementSystem?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 8090

cloudflare:
  api:
    url: https://api.cloudflare.com/client/v4/accounts/ddadeabed2494154764db552710a34c2/ai/run/@cf/meta/llama-3.1-8b-instruct
    key: 8_HvhWtvvgjyrt4qb1IsJtIatochSH_QYtefqsv4
